name: alakon_lang
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  collection: ^1.19.0
  petitparser: ^6.0.2

dev_dependencies:
  lints: ^5.1.1
